version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4321:4321
    working_dir: /app
    command: node dist/server/entry.mjs
    volumes:
      - ./dist:/app/dist
